### ISSUE TITLE
org.jeasy.random.ObjectCreationException is thrown when enum is implementing interface

### ISSUE THREAD

**Issue by aaramg** [j-easy/easy-random#371] opened 2019-10-09 21:46 UTC
I am getting an exception in this scenario, which I guess I should not.

I have an interface:
```
public interface Resolution {
}
```
```
public enum PreSyncCaseResolution implements Resolution {
    CORRECT, WRONG
}
```
```
public class Case {
    private Resolution resolution;
}
```
I set in the parameters ".scanClasspathForConcreteTypes(true)" but when I try to generate random "Case" type object I get this exception informing that "Unable to create a random instance of type interface {packageName}.Resolution"

**Comment by benas** [comment] 2019-10-26 16:30
I'm not able to reproduce the issue. The following test passes with v4.0.0 using your classes:

```java
@Test
public void test() {
   EasyRandomParameters parameters = new EasyRandomParameters()
                                   .scanClasspathForConcreteTypes(true);
   EasyRandom easyRandom = new EasyRandom(parameters);
   Case caze = easyRandom.nextObject(Case.class);
   Assert.assertNotNull(caze);
}
```

I have no exceptions and the field `resolution` in `Case` is randomized to one of the enum values as expected:

![Screenshot 2019-10-26 at 18 23 35](https://user-images.githubusercontent.com/1210553/67622805-47462f00-f81e-11e9-9fdb-bc9518f83970.png)

Here is the project I used: [test371.zip](https://github.com/j-easy/easy-random/files/3775033/test371.zip).

Which version do you use? Can you provide a failing test please?

**Comment by benas** [comment] 2019-11-03 22:02
I'm closing this issue. Please do not hesitate to re-open it if you have a failing test that reproduces the case.

**Closed by benas** 2019-11-03 22:02 UTC
Labels: cannot-reproduce, waiting-for-feedback
