### ISSUE TITLE
[Feature] Add Standard Generation of XMLGregorianCalendar

### ISSUE THREAD

**Issue by LucasKonrath** [j-easy/easy-random#423] opened 2020-07-28 13:52 UTC
In some projects, we used SOAP Stubs, and they couldn't be generated from the get-go because EasyRandom doesn't have a standard randomizer for XMLGregorianCalendar. Though this can easily be circumvented in each project by adding the custom randomizer to the EasyRandomParameters, I think it'd be a pretty useful feature.

![image](https://user-images.githubusercontent.com/27367589/88678847-42701d80-d0c5-11ea-8368-62229a889b7a.png)

**Comment by LucasKonrath** [comment] 2020-07-28 14:27
Added PR https://github.com/j-easy/easy-random/pull/424

**Comment by benas** [comment] 2020-10-09 21:54
Closing this as duplicate of #395 .

**Closed by benas** 2020-10-09 21:54 UTC
