### ISSUE TITLE
Regression: Unable to create a random instance (brother subclasses)

### ISSUE THREAD

**Issue by seregamorph** [j-easy/easy-random#437] opened 2020-11-02 09:52 UTC
Consider this snippet:
```java
import lombok.Data;
import lombok.experimental.Accessors;
import org.jeasy.random.EasyRandom;
import org.jeasy.random.EasyRandomParameters;

public class EasyRandomTest {

    public static void main(String[] args) {
        EasyRandom easyRandom = new EasyRandom(new EasyRandomParameters());

        System.out.println(easyRandom.nextObject(BulkOperationObjectError.class));
    }

    @Data
    @Accessors(chain = true)
    public static class ObjectError {
        private String objectName;
    }

    @Data
    @Accessors(chain = true)
    public static class BulkOperationObjectError extends ObjectError {
        private FieldError fieldError;
    }

    @Data
    @Accessors(chain = true)
    public static class FieldError extends ObjectError {
        @Override
        public FieldError setObjectName(String objectName) {
            super.setObjectName(objectName);
            return this;
        }
    }
}
```

I minimized the code as much as possible. In `4.2.0` it successfully creates a random instance. In `4.3.0-SNAPSHOT` it fails with exception:
```
Exception in thread "main" org.jeasy.random.ObjectCreationException: Unable to create a random instance of type class com.trilogy.restapi.errors.EasyRandomTest$BulkOperationObjectError
	at org.jeasy.random.EasyRandom.doPopulateBean(EasyRandom.java:172)
	at org.jeasy.random.EasyRandom.nextObject(EasyRandom.java:100)
	at com.XXX.restapi.errors.EasyRandomTest.main(EasyRandomTest.java:14)
Caused by: java.lang.IllegalArgumentException: com.trilogy.restapi.errors.EasyRandomTest$BulkOperationObjectError is not assignable from com.XXX.restapi.errors.EasyRandomTest$FieldError
	at org.apache.commons.beanutils.MethodUtils.getAccessibleMethod(MethodUtils.java:793)
	at org.apache.commons.beanutils.PropertyUtilsBean.getWriteMethod(PropertyUtilsBean.java:1319)
	at org.apache.commons.beanutils.PropertyUtilsBean.setSimpleProperty(PropertyUtilsBean.java:2094)
	at org.apache.commons.beanutils.PropertyUtilsBean.setNestedProperty(PropertyUtilsBean.java:1915)
	at org.apache.commons.beanutils.PropertyUtilsBean.setProperty(PropertyUtilsBean.java:2022)
	at org.jeasy.random.util.ReflectionUtils.setProperty(ReflectionUtils.java:153)
	at org.jeasy.random.FieldPopulator.populateField(FieldPopulator.java:102)
	at org.jeasy.random.EasyRandom.populateField(EasyRandom.java:209)
	at org.jeasy.random.EasyRandom.populateFields(EasyRandom.java:198)
	at org.jeasy.random.EasyRandom.doPopulateBean(EasyRandom.java:165)
	... 2 more
```

I did not investigate it deeper yet, but for sure it may become a problem in case of version upgrade.

**Comment by seregamorph** [comment] 2020-11-02 10:30
The regression appears in https://github.com/j-easy/easy-random/commit/12a457121c986c739a15e7354c0cc5145f17fae0 (#402)

**Comment by seregamorph** [comment] 2020-11-02 10:32
cc @arnzel

**Comment by seregamorph** [comment] 2020-11-02 12:24
Simple prototype to reproduce the problem:
```java
import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.apache.commons.beanutils.FluentPropertyBeanIntrospector;
import org.apache.commons.beanutils.PropertyUtilsBean;
import org.junit.jupiter.api.Test;

public class EasyRandomChainSettersTest {

    @Test
    void chainSettersShouldBeRandomized() throws Exception {
        int option = 0; // 0, 1 or 2
        if (option == 1) {
            // leads to fail (in init)
            init1();
        } else if (option == 2) {
            // leads to success (all)
            init2();
        } else {
            // no op
            // leads to fail (in test)
        }

        EasyRandom easyRandom = new EasyRandom(new EasyRandomParameters());

        assertNotNull(easyRandom.nextObject(BulkOperationObjectError.class));
    }

    void init1() throws Exception {
        PropertyUtilsBean propertyUtilsBean = new PropertyUtilsBean();
        propertyUtilsBean.addBeanIntrospector(new FluentPropertyBeanIntrospector());

        FieldError fieldError = new FieldError();
        //fieldError.setObjectName("name");
        propertyUtilsBean.setProperty(fieldError, "objectName", "name");

        BulkOperationObjectError bulkError = new BulkOperationObjectError();
        //bulkError.setObjectName("name");
        propertyUtilsBean.setProperty(bulkError, "objectName", "name");
    }

    void init2() throws Exception {
        PropertyUtilsBean propertyUtilsBean = new PropertyUtilsBean();
        propertyUtilsBean.addBeanIntrospector(new FluentPropertyBeanIntrospector());

        BulkOperationObjectError bulkError = new BulkOperationObjectError();
        //bulkError.setObjectName("name");
        propertyUtilsBean.setProperty(bulkError, "objectName", "name");

        FieldError fieldError = new FieldError();
        //fieldError.setObjectName("name");
        propertyUtilsBean.setProperty(fieldError, "objectName", "name");
    }

    public static class ObjectError {
        private String objectName;

        public ObjectError setObjectName(String objectName) {
            this.objectName = objectName;
            return this;
        }

        public String getObjectName() {
            return objectName;
        }
    }

    public static class BulkOperationObjectError extends ObjectError {
        private FieldError fieldError;
    }

    public static class FieldError extends ObjectError {
        @Override
        public FieldError setObjectName(String objectName) {
            super.setObjectName(objectName);
            return this;
        }
    }
}
```

Pay attention to (option=0, 1 or 2). With different values you will have different results. It looks like the root issue is in the `beanutils`

**Comment by seregamorph** [comment] 2020-11-02 12:56
The issue is in `org.apache.commons.beanutils.FluentPropertyBeanIntrospector` at line 144. You can see wrong call: it sets `FieldError FieldError.setObjectName(java.lang.String)` as a setter for super `java.beans.PropertyDescriptor[name=objectName; propertyType=class java.lang.String; readMethod=public java.lang.String org.jeasy.random.EasyRandomChainSettersTest$ObjectError.getObjectName()]` and **caches it in the internal cache of java.beans.Introspector**. That's the result of bad design of `java.beans.PropertyDescriptor` (mutable and cacheable).

The next call of `BulkOperationObjectError` setter reuses cached setter (the cached method does not match).

**Comment by seregamorph** [comment] 2020-11-02 13:32
I raised an issue https://issues.apache.org/jira/browse/BEANUTILS-541
To address an issue in easy-random we have at least two ways:
- write our own setters resolver (complicated, we should respect all possible issues like assignment rules, primitive types, etc), the impl can be copied from spring-core `BeanUtils`
- Workaround with cache eviction:
```java
// ReflectionUtils.java
...
        } catch (IntrospectionException | IllegalAccessException e) {
            try { // to call fluent setter
                flushIntrospectorCaches(object.getClass());
                PROPERTY_UTILS_BEAN.setProperty(object, field.getName(), value);
            } catch (NoSuchMethodException noSuchMethodException) {
                // otherwise, set field using reflection
                setFieldValue(object, field, value);
            }
        }
    }

    private static void flushIntrospectorCaches(Class<?> type) {
        // https://issues.apache.org/jira/browse/BEANUTILS-541
        Introspector.flushFromCaches(type);
        Class<?> superType = type.getSuperclass();
        if (superType != null && superType != Object.class) {
            flushIntrospectorCaches(superType);
        }
    }
```

**Comment by benas** [comment] 2020-11-02 20:38
@seregamorph Thank you very much for raising this regression and for your investigation! Really appreciated 👍 

I would opt for option 2, flushing the bean introspector cache until this is fixed in apache commons-beanutils. You can open a PR for that, otherwise let me know and I will take care of the change.

> I raised an issue https://issues.apache.org/jira/browse/BEANUTILS-541

The affect version in this ticket is 1.9.0 -> 1.9.3. However, we are using commons-beanutils v1.9.4 here and it seems that the issue is still happening with that version. Should you include 1.9.4 in the affect version as well in BEANUTILS-541?

**Comment by seregamorph** [comment] 2020-11-02 21:02
The version 1.9.4 was added (on the ticket creation it was not suggested). I will make more investigation on option 2 and provide the PR tomorrow.

**Comment by seregamorph** [comment] 2020-11-03 11:34
I've found one more related regression: if the field has fluent (a.k.a. chained) setter, and the subclass overrides field (not setter):
```java
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

public class EasyRandomOverridenFieldTest {

    @Test
    void chainSettersShouldBeRandomized() {
        EasyRandom easyRandom = new EasyRandom(new EasyRandomParameters());

        SubClass value = easyRandom.nextObject(SubClass.class);

        assertFalse(((BaseClass) value).field.isEmpty());
        assertTrue(value.field != 0);
    }

    public static class BaseClass {

        // field overriden (note: not setter)
        private String field;

        public BaseClass setField(String field) {
            this.field = field;
            return this;
        }
    }

    public static class SubClass extends BaseClass {

        // note: field overriden
        private int field;
    }
}
```
it fails with:
```
Caused by: java.lang.IllegalArgumentException: Cannot invoke org.jeasy.random.EasyRandomOverridenFieldTest$BaseClass.setField on bean class 'class org.jeasy.random.EasyRandomOverridenFieldTest$SubClass' - argument type mismatch - had objects of type "java.lang.Integer" but expected signature "java.lang.String"
	at org.apache.commons.beanutils.PropertyUtilsBean.invokeMethod(PropertyUtilsBean.java:2196)
	at org.apache.commons.beanutils.PropertyUtilsBean.setSimpleProperty(PropertyUtilsBean.java:2109)
	at org.apache.commons.beanutils.PropertyUtilsBean.setNestedProperty(PropertyUtilsBean.java:1915)
	at org.apache.commons.beanutils.PropertyUtilsBean.setProperty(PropertyUtilsBean.java:2022)
	at org.jeasy.random.util.ReflectionUtils.setProperty(ReflectionUtils.java:153)
	at org.jeasy.random.FieldPopulator.populateField(FieldPopulator.java:102)
	at org.jeasy.random.EasyRandom.populateField(EasyRandom.java:209)
	at org.jeasy.random.EasyRandom.populateFields(EasyRandom.java:198)
	at org.jeasy.random.EasyRandom.doPopulateBean(EasyRandom.java:165)
	... 65 more
Caused by: java.lang.IllegalArgumentException: argument type mismatch
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.commons.beanutils.PropertyUtilsBean.invokeMethod(PropertyUtilsBean.java:2128)
	... 73 more
```

Such class design is not totally good, but in any case it was working fine earlier (both fields were filled with random values), so if we respect back compatibility, this should be addressed.

**Comment by seregamorph** [comment] 2020-11-03 12:19
The second problem with overriden field cannot be workarounded with caches flush and recreating the `PropertyUtilsBean` object. See #438 with detailed explanations

**Closed** 2020-11-03 22:35 UTC
Labels: waiting-for-feedback
