### ISSUE TITLE
Possibility to disable cache

### ISSUE THREAD

**Issue by mjureczko** [j-easy/easy-random#449] opened 2020-12-15 12:55 UTC
EasyRandom caches the generated objects to speed things up when numerous objects are requested. However, it is not a perfect match for every use case. Sometimes one may need more unique objects. Reusing the same objects may create inter tests dependencies when using easy-random for generating test data, which can be especially nasty when the objects are mutable. When using recursive data structures, the cache can create infinite loops (A->B->C->B...)

Currently, the only possibility to not use cache is to set `objectPoolSize` to a large value. Effectively, it can cause that the cache will never fill up and as consequence, will never be used to fetch an object. However, such an approach has a significant and unnecessary memory footprint - each object created by the easy-random will be kept in memory, but none will be reused.

If an additional property for disabling cache is in line with the vision of this project, I will be happy to provide an MR with such solution.

**Comment by JohannesBe** [comment] 2020-12-20 13:42
For my back-reference implementation (see https://github.com/j-easy/easy-random/issues/444) I would also like the possibility of turning the cache off. Might I suggest using a value of `0` for the `objectPoolSize` in order to accomplish this? I feel this would have non-breaking impact* whilst keeping the API-compatibility maximal at the same time.

\* this value is currently completely impossible, since the setter has a check for this:
```
    public void setObjectPoolSize(int objectPoolSize) {
        if (objectPoolSize < 1) {
            throw new IllegalArgumentException("objectPoolSize must be >= 1");
        }
        this.objectPoolSize = objectPoolSize;
    }
```

**Comment by JohannesBe** [comment] 2020-12-20 13:44
There might be more strings attached to doing this however, see the docstring of `RandomizationContext`:
>  * It contains a map acting as a cache of populated beans to avoid infinite recursion.

Not sure what that's about.

**Comment by ldmi3i** [comment] 2020-12-20 19:08
> There might be more strings attached to doing this however, see the docstring of `RandomizationContext`:
> 
> > * It contains a map acting as a cache of populated beans to avoid infinite recursion.
> 
> Not sure what that's about.

I think if there is class A and class B. And class A have field B b , class B have field A a . It causes infinite recursion because without using of pool each class will try populate this reference with new object instead of using already populated. Pool bounds process of creation new beans with pool size.
So disabling of pool is dangerous and can cause infinite recursion.

**Comment by JohannesBe** [comment] 2020-12-20 20:01
But isn't that what the recursion depth setting is for?

**Comment by mjureczko** [comment] 2020-12-21 10:38
I tested @JohannesBe theory about recursion depth and it is correct. I implemented a change that disabled the cache and generated the A and B classes (as described by @ldmi3i) and the recursion was cut off on the configured recursion depth with null values. So the cache does not avoid infinite recursion, but rather creates it as I described in the issue report.

The disabling cache is not as simple at allowing the objectPoolSize to equals 0 as it will cause the cache logic to think that an empty cache is full of data and as a consequence, it will try to fetch non-existing instances. So the cache logic must be also adjusted which by the way is not a very complex task.

**Comment by JohannesBe** [comment] 2020-12-21 14:27
> So the cache logic must be also adjusted which by the way is not a very complex task.

Is what I did in the MR sufficient? Or do you mean it needs additional changes?

**Comment by mjureczko** [comment] 2020-12-21 14:43
I was not aware of your MR when making this comment. I believe that your MR is OK :+1:

**Comment by benas** [comment] 2021-01-13 22:09
Sorry for not being active here until now.

@mjureczko 

> Possibility to disable cache #449

This is a duplicate of #182, so I will close it as duplicate.

> Currently, the only possibility to not use cache is to set objectPoolSize to a large value.

Yes, as mentioned by @PascalSchumacher here: https://github.com/j-easy/easy-random/issues/182#issuecomment-249233331. This does not seem to be clearly documented, so I updated the wiki accordingly, see https://github.com/j-easy/easy-random/wiki/Randomization-parameters#object-pool-size.

Now I just wanted to add a quick comment in regards to `the *only* possibility to not use cache is to ..`. I'm a proponent of the "There should be one-- and preferably only one --obvious way to do it" principle from the [The Zen of Python](https://www.python.org/dev/peps/pep-0020/). GoLang has another set of awesome principles as well: [The Zen of Go](https://the-zen-of-go.netlify.app). While I'm not a pythonist nor a gopher, I believe those principles are universal and could be applied to any programming language. I try to apply these principles as much as possible in all jeasy projects to keep things simple and stupid. With that said, I think the fact of having a single way to disable caching in ER is a good thing.

> However, such an approach has a significant and unnecessary memory footprint - each object created by the easy-random will be kept in memory, but none will be reused.

Well, that's exactly the definition of not caching. Not caching objects means continuously creating new objects and not reusing them. You can't have "no caching" and "low memory footprint" at the same time, you have to make a trade-off here.

> If an additional property for disabling cache is in line with the vision of this project, I will be happy to provide an MR with such solution. 

No, there is no plan to add such property since there is already a way to do that as you mentioned and as I explained previously, and adding a new way to do the same thing would be confusing (which way is better, which way takes precedence over the other, etc). Please note that the project is in [maintenance mode](https://github.com/j-easy/easy-random#project-status) now, and only bug fixes will be addressed. If you still think there is a need for a second way of disabling caching, then you can do it in a fork.

Thank you for opening this issue anyway and thanks to @JohannesBe and @ldmi3i for the follow up!

**Closed by benas** 2021-01-13 22:09 UTC

**Comment by mjureczko** [comment] 2021-01-21 07:54
@benas, I only would like to note that this passage
> Well, that's exactly the definition of not caching. Not caching objects means continuously creating new objects and not reusing them. You can't have "no caching" and "low memory footprint" at the same time, you have to make a trade-off here.
is a bit misleading with regard to easy-random. Using large values of `objectPoolSize` results in keeping references to all created objects, which in turn prevents the garbage collector from releasing the memory allocated for those objects. So, effectively it is a memory leak.

**Comment by benas** [comment] 2021-01-21 23:22
@mjureczko, I disagree on this:

> Using large values of objectPoolSize results in keeping references to all created objects, which in turn prevents the garbage collector from releasing the memory allocated for those objects. So, effectively it is a memory leak.

If you use a JDBC connection pooling library (like hikari, dbcp, c3p0, etc) and set a parameter like `connectionPoolSize=10000`, then that library will, upon your request, create 10000 connection objects for you and those objects will be held in memory during the lifetime of your application to be (re)used by your application's threads. Is that a memory leak? Definitely not. If you disagree, you can try to open a similar issue against one of these libraries and see what you get.

A big memory consumption is qualified as a memory leak when objects are unintentionally held in memory incorrectly. Here, the action is explicit, you are intentionally instructing the library to create a large number of connection objects (in the case of connection pooling libraries) or random objects (in the case of ER) to be reused whenever the threshold is exceeded.

**Comment by mjureczko** [comment] 2021-01-22 14:27
@benas the situation with easy-random differs from pooling libraries as the libraries cache the connections for later reuse. In easy-random the wiki says
> Heads up: If you want to disable caching, you need to set the object pool size to a sufficiently large value.

but the cache is not really disabled. The objects are cached but not reused, so in onther words unintentionally held in memory.

**Comment by benas** [comment] 2021-01-22 20:18
> The objects are cached but not reused, so in onther words unintentionally held in memory.

That's not correct, objects from the pool are re-used whenever the threshold is exceeded, here is an example:

```java
@Test
void testObjectPool() {
    class Person {
        Person parent;
        List<Person> friends;
    }

    EasyRandomParameters parameters = new EasyRandomParameters()
            .objectPoolSize(2) // at most two instances, one for the person and one for its parent
            .collectionSizeRange(3, 3); // exactly 3 friends
    EasyRandom easyRandom = new EasyRandom(parameters);
    Person person = easyRandom.nextObject(Person.class);

    Assertions.assertThat(person).isNotSameAs(person.parent);
    Assertions.assertThat(person.friends).allMatch(friend -> friend == person || friend == person.parent);
    // you can check with the hash code of each object: all friends will be re-used from the object pool
    System.out.println("person = " + person);
    System.out.println("person.parent = " + person.parent);
    System.out.println("person.friends = " + person.friends);
}
```

This test passes and prints:

```
person = org.jeasy.random.RandomizationTest$1Person@56cdfb3b
person.parent = org.jeasy.random.RandomizationTest$1Person@2b91004a
person.friends = [org.jeasy.random.RandomizationTest$1Person@56cdfb3b, org.jeasy.random.RandomizationTest$1Person@2b91004a, org.jeasy.random.RandomizationTest$1Person@2b91004a]
```

You can clearly see that with an `objectPoolSize=2`, ER will generate at most two `Person` objects, which will be assigned to the person and its parent, and then all friends will be taken from the pool (same for the parent's friends, etc until the `randomizationDepth` is reached). So ER does re-use objects from the pool.

**Comment by mjureczko** [comment] 2021-01-23 08:37
@benas you're right, when using small values for `objectPoolSize` it works like a cache, but you're ignoring the fact that the use case discussed in this issue is to disable the cache. Easy-random wiki says:
> Heads up: If you want to disable caching, you need to set the object pool size to a sufficiently large value.

Following this advice, the `objectPoolSize` should not be set to 2, but for instance to `Integer.MAX_VALUE`. However, this does not disable the cache. All created objects are still cached (stored in memory). What really happens, is that the objects are not reused. Cached objects are not used until the cache size reaches the value set in `objectPoolSize`. When setting
> the object pool size to a sufficiently large value

the condition is never met. So following the wiki advice turns the cache into a memory leak.

**Comment by benas** [comment] 2021-01-25 00:11
> @benas you're right, when using small values for objectPoolSize it works like a cache

I used a small value to make the example easy to understand, but the behaviour is the same for small or large values. You said it: it works "like" a cache and indeed, In ER, the object pool acts as a cache (as mentioned in the [javadocs](https://github.com/j-easy/easy-random/blob/master/easy-random-core/src/main/java/org/jeasy/random/RandomizationContext.java#L35)), but is obviously not a real cache. A real cache like ehcache or memcached has automatic object eviction. An object pool does not have that capability. And this is what you seem to be confusing. Objects from the pool should not be automatically evicted, otherwise ER cannot solve the infinite recursion problem. If you are expecting objects from the pool to be automatically evicted, then your expectation is wrong and your feature request is not valid: there is no cache to disable here, there is an object pool with a configurable size. And BTW, I  have updated the wiki too quickly by using your term "disable caching" which is confusing, so I removed it.

> you're ignoring the fact that the use case discussed in this issue is to disable the cache.

I'm not ignoring that, I already explained how ER allows you to address this case in my [previous comment](https://github.com/j-easy/easy-random/issues/449#issuecomment-759770021).

> What really happens, is that the objects are not reused. Cached objects are not used until the cache size reaches the value set in objectPoolSize.

So even with a [complete example that shows you that objects are re-used](https://github.com/j-easy/easy-random/issues/449#issuecomment-765660314) you are still claiming that objects are not re-used.. Of course objects will not be re-used from the pool until the number of randomly objects generated reaches the value of `objectPoolSize`. It does not make sense to start re-using things before that threshold. A connection pooling library will continuously create new connections until the number of created connections reaches `connectionPoolSize`, and only then it will start serving connections from the pool for new connection requests. That's why just like connection pooling libraries where it is up to you to wisely choose the initial connection pool size, you have to wisely choose the `objectPoolSize` in ER depending on your case. In the previous example, if I want to have a list of 10 **distinct** friends, I would set `objectPoolSize=12` (person + parent + 10 friends). If I want to have a list of 10.000 **distinct** friends, I can set `objectPoolSize=10002`. Now, if I don't mind having 10.000 **duplicate**  friends, I can set `objectPoolSize=10` for example. There is no best value for `objectPoolSize`, it depends on the use case. There is no memory leak, I'm explicitly telling ER to generate that number of distinct random objects (and start re-using them after that limit).
