### ISSUE TITLE
Does easy-random-bean-validation supports multiple annotation on same field?

### ISSUE THREAD

**Issue by ghilainm** [j-easy/easy-random#411] opened 2020-04-21 07:32 UTC
I have a question which I could not find the answer in the documentation:

Does easy-random-bean-validation support multiple annotations on the same field? If, yes, how is it implemented?

**Comment by ghilainm** [comment] 2020-04-24 16:45
So I can already answer part of the question, it seems it choose randomly one of the annotation. So results are random. This created issues on my side because values are randomly valid and randomly not.

This piece of code is the culprit.
```
public Randomizer<?> getRandomizer(Field field) {
        Iterator var2 = this.annotationHandlers.entrySet().iterator();

        Class annotation;
        BeanValidationAnnotationHandler annotationHandler;
        do {
            if (!var2.hasNext()) {
                return null;
            }

            Entry<Class<? extends Annotation>, BeanValidationAnnotationHandler> entry = (Entry)var2.next();
            annotation = (Class)entry.getKey();
            annotationHandler = (BeanValidationAnnotationHandler)entry.getValue();
        } while(!ReflectionUtils.isAnnotationPresent(field, annotation) || annotationHandler == null);
        System.out.println(field.getDeclaringClass() + " - "+ annotationHandler.getClass());
        return annotationHandler.getRandomizer(field);
    }
```

**Comment by benas** [comment] 2020-10-18 21:58
> I could not find the answer in the documentation:

This is documented here: https://github.com/j-easy/easy-random/wiki/known-limitations#bean-validation.

Closing this as duplicate of #418.

**Closed by benas** 2020-10-18 21:58 UTC
Labels: question
