### ISSUE TITLE
Unable to create a random instance (Generic Types)

### ISSUE THREAD

**Issue by messaoudi-mounir** [j-easy/easy-random#386] opened 2020-01-30 10:53 UTC
The test bellow fail 

```
public abstract class ReferencedObject {
 private UUID uuid;
 public ReferencedObject(){
  }
}

public class A extends ReferencedObject  {
   public A(){}
   // some code here 
}
public class B extends ReferencedObject  {
    public B(){}
   // some code here 
}

public class DataObjectReference<T extends ReferencedObject> {
  private String contentType;
  private T referencedObject;

  public DataObjectReference() {
  }
  public DataObjectReference(T referencedObject) {
    this.referencedObject = referencedObject;
  }
}

public class C {
     private DataObjectReference<A> parent;
     public C(){}
    // some code here 
}


EasyRandom easyRandom = new EasyRandom();
C pojo = easyRandom.nextObject(C.class);

}

```
// error message

 Unable to create a random instance of type class ReferencedObject

**Comment by benas** [comment] 2020-03-04 23:46
Thank you for opening this issue. This is a duplicate of #375 . This is a [known limitation](https://github.com/j-easy/easy-random/wiki/known-limitations#type-erasure) and is not supported due to type erasure.

You need to use a custom randomizer for the generic type.

**Closed by benas** 2020-03-04 23:46 UTC
