### ISSUE TITLE
Default final fields are randomized when using Lombok @Builder

### ISSUE THREAD

**Issue by NickUK** [j-easy/easy-random#364] opened 2019-07-05 09:05 UTC
Using easy-random-core:4.0.0

When using lombok `@Builder` with a class (like the one below), some of the final fields with default values are randomized:
```
@Builder
@Data
public class BeanWithDataAndBuilder {

    private final Integer defaultInteger = 1;

    private final int defaultInt = 1;

    private final String defaultString = "default";

    private final Boolean defaultBoolean = false;

    private final boolean defaultBool = false;

    private String randomizeMe;

}
```

I would expect the following code to pass:
```
        // Given
        EasyRandomParameters parameters = new EasyRandomParameters().overrideDefaultInitialization(false).collectionSizeRange(1, 1);
        EasyRandom easyRandom = new EasyRandom(parameters);

        // When
        BeanWithDataAndBuilder bean = easyRandom.nextObject(BeanWithDataAndBuilder.class);

        // Then
        assertThat(bean.getDefaultInteger()).isEqualTo(1);
        assertThat(bean.getDefaultInt()).isEqualTo(1);
        assertThat(bean.getDefaultString()).isEqualTo("default");
        assertThat(bean.getDefaultBoolean()).isEqualTo(false);
        assertThat(bean.isDefaultBool()).isEqualTo(false);
        assertThat(bean.getRandomizeMe()).isNotNull();
```

However all the fields get randomized.

I did find a way of creating this class:
```
        BeanWithDataAndBuilder.BeanWithDataAndBuilderBuilder tmpBean = easyRandom.nextObject(BeanWithDataAndBuilder.BeanWithDataAndBuilderBuilder.class);
        BeanWithDataAndBuilder bean = tmpBean.build();
```
This does work as expected. Perhaps the builder class could be detected? I think the issue is that the objenesis generated constructor that is being used doesn't pick up any of the defaults.

**Comment by benas** [comment] 2019-10-26 17:25
I was able to reproduce the case. Easy Random tries to create an instance of the target bean using the default constructor (A Java Bean should provide a default constructor btw), and falls back to objenesis if no such constructor exists.

However, looks like this is a bug in lombok: combining `@Data` with `@Builder` removes the default constructor (See https://github.com/rzwitserloot/lombok/issues/816).

Trying to add `@NoArgsConstructor` results in a compilation error (reported in https://github.com/rzwitserloot/lombok/issues/1389).

So when this combination of lombok annotations is fixed, Easy Random should work as expected.

I'm closing this as duplicate of #228 (See [known limitations](https://github.com/j-easy/easy-random/wiki/known-limitations#types-with-no-default-constructor) section).

**Closed by benas** 2019-10-26 17:25 UTC
