### ISSUE TITLE
Error when using with Immutables Library / Can properties set by Setter Methods  

### ISSUE THREAD

**Issue by arnzel** [j-easy/easy-random#388] opened 2020-02-13 10:22 UTC
See here : https://github.com/immutables/immutables/issues/1152

**Comment by arnzel** [comment] 2020-02-17 08:35
Problem seems to be that values of fields are set by reflection directly and not by setter. Can Easy Random configured in the way so that fields can be filled by setters ?

**Comment by benas** [comment] 2020-03-05 21:23
This is similar to #274 , but let me do a quick recap. Easy Random was initially designed to randomize Java Beans only (which by definition provide a setter for each property) and was relying on Apache commons-beanutils to set properties through setters. This design decision turned out to be restrictive and many people started quickly asking to relax things and make it possible to randomize types that do not provide setters. This is when we removed the dependency to Apache commons-beanutils and where the field setting mechanism changed from using setters to using reflection.

Now in #274, the suggestion was to make this configurable, and I shared my attempt to do that with a new parameter called `enforceJavaBeanConventions` (See [this comment](https://github.com/j-easy/easy-random/issues/274#issuecomment-457951257) and the attached patch). However this option was abandoned because Easy Random cannot and should not enforce any convention. It should be liberal in what it accepts: If the user's type provides a setter, then the setter should be used to set the field, otherwise, Easy Random can fallback to reflection.

This is what I implemented in e924b7e186facb3216bf2e8ac6de24d40d6c6cc9, and deployed in 4.2.0-SNAPSHOT. Can you give it a try and let me know what do you think? Thank you upfront!

**Comment by arnzel** [comment] 2020-03-06 10:13
Hi thanks for explanation, i will try when i have time

**Comment by arnzel** [comment] 2020-03-06 12:42
Hi i tried it but there is  a problem which is specific to Immuables Library. Immutables use fluent setters so it does not strictly follow the bean conventions.

I think this is a apecial case. In general i think its a good idea to first try using setter methods and if this is not possible using reflections.

Maybe i have to provide something like a custom randomizer for this classes.Other idea would be to change "strategy order" to

1. try using custom field populator
2. try using setter
3. try using reflections

but i think this makes it too complicated

**Comment by arnzel** [comment] 2020-03-06 12:46
Other idea would be to use a PropertyDescriptor which also accepts fluent setters. that would be awesome

**Comment by benas** [comment] 2020-03-06 20:11
> there is a problem which is specific to Immuables Library. Immutables use fluent setters so it does not strictly follow the bean conventions.

That's explain it. Fluent setters are not compatible with Java Beans conventions. I remember having the [same issue but with lombok](https://github.com/j-easy/easy-random/issues/42#issuecomment-165565727) when configured to generate fluent setters.

For this reason, I'm closing this issue.

> In general i think its a good idea to first try using setter methods and if this is not possible using reflections.

Yes, this is what I did in the aforementioned commit and which I will keep and include in the upcoming 4.2 release.

> Other idea would be to use a PropertyDescriptor which also accepts fluent setters. that would be awesome

This is what I used: https://github.com/j-easy/easy-random/commit/e924b7e186facb3216bf2e8ac6de24d40d6c6cc9#diff-9c3368b6d38ed8bbb04db27b0c69e1c7R136. However, I'm not sure it accepts fluent setters. Here is quick example:

```java
public class Point {
    
    private int x;
    
    public int getX() {
        return x;
    }
    
    public Point setX(int x) {
        this.x = x;
        return this;
    }
}

@Test
void testPropertyDescriptorWithFluentSetter() throws Exception {
    PropertyDescriptor propertyDescriptor = new PropertyDescriptor("x", Point.class);
    Method setter = propertyDescriptor.getWriteMethod();
    assertThat(setter).isNotNull();
}
```

This fails with `java.beans.IntrospectionException: Method not found: setX`. So if you have a reference where it is said that `PropertyDescriptor` is able to introspect fluent setters, I would be grateful if you can share it.

**Closed by benas** 2020-03-06 20:11 UTC
Labels: enhancement, waiting-for-feedback

**Comment by arnzel** [comment] 2020-03-07 13:44
This one might be an option but its part of commons beanutils
This one might be an option but its part of commons beanutils
https://commons.apache.org/proper/commons-beanutils/javadocs/v1.9.0/apidocs/org/apache/commons/beanutils/FluentPropertyBeanIntrospector.html

**Comment by benas** [comment] 2020-03-09 21:34
Thanks for sharing the link!

I don't know how this is supposed to work because I tried to follow its Javadoc and added it a bean introspector after adding the default one like mentioned here:

```
An instance of this class is intended to collaborate with a DefaultBeanIntrospector 
object. So best results are achieved by adding this instance as custom 
BeanIntrospector after the DefaultBeanIntrospector object.
```

But I still have the exception with this example:

```java
public class Point {

    private int x;

    public int getX() {
        return x;
    }

    public Point setX(int x) {
        this.x = x;
        return this;
    }
}

@Test
void testPropertyDescriptorWithFluentSetter() throws Exception {
    // tried this as well
    // PropertyUtils.clearDescriptors();
    // PropertyUtils.addBeanIntrospector(DefaultBeanIntrospector.INSTANCE);
    PropertyUtils.addBeanIntrospector(new FluentPropertyBeanIntrospector());
    PropertyDescriptor propertyDescriptor = new PropertyDescriptor("x", Point.class);
    Method setter = PropertyUtils.getWriteMethod(propertyDescriptor);
    assertThat(setter).isNotNull();
}
```

The problem is that `new PropertyDescriptor("x", Point.class)` fails with `java.beans.IntrospectionException: Method not found: setX` before even reaching `PropertyUtils.getWriteMethod(propertyDescriptor)`.. So I don't know how this API is supposed to be used since `PropertyUtils.getWriteMethod` accepts a `java.beans.PropertyDescriptor` which I cannot create for types with fluent setters..

Do you see the issue?

I will proceed with the release now and keep an eye on this. If you have a working example, we can see how to integrate it to support fluent setters. I'm not against putting apache commons beanutils back if it adds value regarding introspecting fluent setters.

**Comment by enedzvetsky** [comment] 2020-03-19 21:19
I would like to disable this enhancement but looks like it's impossible in 4.2.0
Can please you add an additional setting to EasyRandomParameters?

**Comment by benas** [comment] 2020-03-19 21:32
@enedzvetsky Please open a separate issue for that.

**Comment by arnzel** [comment] 2020-03-26 19:36
Hi @benas  i also tried using FluentPropertyBeanIntrospector and it seems to me that it works , see https://github.com/j-easy/easy-random/pull/402
