### ISSUE TITLE
Ignore the NotNull/NotBlank/NotEmpty annotations in multiple validation annotations cases

### ISSUE THREAD

**Issue by dadiyang** [j-easy/easy-random#436] opened 2020-11-02 00:33 UTC
As we known, there's a limitation in generating random value with multi-validation annotations. 

But it must be a way to optimize this functionality. 
There are some suggestions:

1. just ignore the NotNull/NotBlank/NotEmpty annotations, because Handling these annotations are unnecessary for generating random value

2. always use the first annotation in the field so that users can choose anyone themselves

**Comment by benas** [comment] 2020-11-05 22:07
Thank you for these suggestions, but none of them would solve the issue. Here is why, consider the following example:

```java
class Person {
    @NotBlank
    @Size(min = 5, max = 10)
    @Pattern(regexp = "a*b")
    String name;
}
```

1. I understand we could ignore `NotBlank` here, but the issue is still present on how to generate a random valid value according to the remaining two annotations (ie a String conform to the regexp `a*b` **and** having a length in [5,10] range). Basically, ignoring `NotNull/NotBlank/NotEmpty` does not work as soon as you have more than two annotations on the field.

2. Always using the first annotation would not work since `Field#getDeclaredAnnotations` does not specify in which order annotations are returned. And even if the order of returned annotations is consistent (according to [1](https://stackoverflow.com/questions/16756291/is-java-annotation-order-persistent) and [2](https://stackoverflow.com/questions/28067074/java-annotations-reflection-ordering/30222541)) , taking the first annotation only might not be sufficient. In the previous example, this means I need to choose between either `@Size` or `@Pattern`, but I want both.

In sum, the issue with multiple validation annotations is that Easy Random provides a handler per annotation. It is not possible to *statically* interpret multiple validation contraints (imagine all the combinations..) and return a randomizer that generates a random value that is valid according to the combined validation logic. Some alternatives have been described in #418 and #351.

I'm closing this issue for now but feel free to add a comment if needed.

**Closed by benas** 2020-11-05 22:07 UTC
